version: '2'

services:
  php:
    container_name: cpa-php
    build: ./php
    volumes:
      - ./app:/app
    working_dir: /app

  web:
    container_name: cpa-nginx
    build: ./nginx
    volumes:
      - ./app:/app
    depends_on:
      - php
      - mysql
      - redis
      - cron
    ports:
      - "80:80"

  mysql:
    container_name: cpa-mysql
    image: mysql:5.6.34
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: cpa_tracker
    volumes:
      - ./mysql/data:/var/lib/mysql
    command: mysqld --sql_mode=""
    user: mysql # MacOS

  redis:
    container_name: cpa-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    user: redis # MacOS

  cron:
    container_name: cpa-cron
    build: ./cron
